handler: handlers/tempTags.getScanHistoryDataForProduct
name: ${self:custom.constants.defaults.prefix}${self:service}-temptags-getScanHistoryDataForProduct
events:
  - http:
      path: /temptags/scanhistory/{productId}
      method: get
      cors: true
      authorizer:
        name: customauthorizer
        resultTtlInSeconds: 0
        identitySource: method.request.header.Authorization
