handler: handlers/tempTags.saveTempTag
name: ${self:custom.constants.defaults.prefix}${self:service}-temptags-save
events:
  - http:
      path: /temptags
      method: post
      cors: true
      authorizer:
        name: customauthorizer
        resultTtlInSeconds: 0
        identitySource: method.request.header.Authorization
