handler: handlers/dummy/collectiontypes.getCollectionTypes
name: ${self:custom.constants.defaults.prefix}${self:service}-type-get
events:
  - http:
      path: /types
      method: get
      cors: true
      authorizer: 
        name: customauthorizer
        resultTtlInSeconds: 0
        identitySource: method.request.header.Authorization