handler: handlers/locations.getZoneProductsOnFloor
name: ${self:custom.constants.defaults.prefix}${self:service}-floorzoneproducts
events:
  - http:
      path: /floorzoneproducts/{id}
      method: get
      cors: true
      # authorizer:
      #   name: customauthorizer
      #   resultTtlInSeconds: 0
      #   identitySource: method.request.header.Authorization
      documentation:
          summary: "Get Products in zones on a floor"
          description: "Get list of zones, along with products present in them, of a specific floor"
          requestHeaders:
          -
            name: "Authorization"
            description: "Custom Authorizer Header Token"
          pathParams:
            -
              name: "floorId"
              required: true
              description: "ID of the attribute you want to get details of"
          methodResponses:
            -
              statusCode: "200"
              responseBody:
                description: "Response body description"
              responseHeaders:
                -
                  name: "x-superheader"
                  description: "this is a super header"
              responseModels:
                "application/json": "CreateResponse"
            -
              statusCode: "400"
              responseModels:
                "application/json": "ErrorResponse"