handler: handlers/locations.saveLocation
timeout: 30
events:
  - http:
      path: locations
      method: post
      cors: true
      authorizer:
        name: customauthorizer
        resultTtlInSeconds: 0
        identitySource: method.request.header.Authorization