handler: handlers/nfcTag.getNfcTagbyId
name: ${self:custom.constants.defaults.prefix}${self:service}-nfctag-getById
events:
  - http:
      path: /nfctags/{id}
      method: get
      cors: true
      authorizer:
        name: customauthorizer
        resultTtlInSeconds: 0
        identitySource: method.request.header.Authorization
