handler: handlers/nfcTag.updateNfcTag
name: ${self:custom.constants.defaults.prefix}${self:service}-nfctag-update
events:
  - http:
      path: /nfctags/{id}
      method: put
      cors: true
      authorizer:
         name: customauthorizer
         resultTtlInSeconds: 0
         identitySource: method.request.header.Authorization
