handler: handlers/shipment.getShipmentsForMobile
name: ${self:custom.constants.defaults.prefix}${self:service}-getForMobile
events:
  - http:
      path: /carrier/
      method: get
      cors: true
      authorizer:
        name: customauthorizer
        resultTtlInSeconds: 0
        identitySource: method.request.header.Authorization
