handler: handlers/device.getDevicebyId
name: ${self:custom.constants.defaults.prefix}${self:service}-devices-getById
events:
  - http:
      path: /devices/{id}
      method: get
      cors: true
      # authorizer:
      #   name: customauthorizer
      #   resultTtlInSeconds: 0
      #   identitySource: method.request.header.Authorization