handler: handlers/device.link
name: ${self:custom.constants.defaults.prefix}${self:service}-devices-link
events:
  - http:
      path: /device/link
      method: put
      cors: true
      authorizer: 
        name: customauthorizer
        resultTtlInSeconds: 0
        identitySource: method.request.header.Authorization
