handler: handlers/device.updateDeviceStatus
name: ${self:custom.constants.defaults.prefix}${self:service}-devices-updateStatus
events:
  - http:
      path: /deviceStatus
      method: put
      cors: true
      # authorizer:
      #    name: customauthorizer
      #    resultTtlInSeconds: 0
      #    identitySource: method.request.header.Authorization
