handler: handlers/things.getThings
name: ${self:custom.constants.defaults.prefix}${self:service}-beacons-get
events:
  - http:
      path: /beacons
      method: get
      cors: true
      authorizer: 
        name: customauthorizer
        resultTtlInSeconds: 0
        identitySource: method.request.header.Authorization