handler: handlers/trackingreports.pointLocationTracking
name: ${self:custom.constants.defaults.prefix}${self:service}-pointLocationTracking
timeout: 30
events:
  - http:
      path: /pointlocation-tracking
      method: get
      cors: true
      authorizer: 
        name: customauthorizer
        resultTtlInSeconds: 0
        identitySource: method.request.header.Authorization
