handler: handlers/trackingreports.rawLocationTracking
name: ${self:custom.constants.defaults.prefix}${self:service}-rawLocationTracking
timeout: 30
events:
  - http:
      path: /rawlocation-tracking
      method: get
      cors: true
      authorizer: 
        name: customauthorizer
        resultTtlInSeconds: 0
        identitySource: method.request.header.Authorization
