handler: handlers/trackingreports.userLocatorMap
name: ${self:custom.constants.defaults.prefix}${self:service}-userLocatorMap
timeout: 30
events:
  - http:
      path: /user-locator-map
      method: get
      cors: true
      # authorizer: 
      #  name: customauthorizer
      #  resultTtlInSeconds: 0
      #  identitySource: method.request.header.Authorization
