handler: handlers/trackingreports.userEntranceHistory
name: ${self:custom.constants.defaults.prefix}${self:service}-userEntranceHistory
timeout: 30
events:
  - http:
      path: /user-entrance-history/{userId}/{locationType}/{location}/{dt}
      method: get
      cors: true
      authorizer: 
        name: customauthorizer
        resultTtlInSeconds: 0
        identitySource: method.request.header.Authorization
