handler: handlers/trackingreports.userEntrance
name: ${self:custom.constants.defaults.prefix}${self:service}-userEntrance
timeout: 30
events:
  - http:
      path: /user-entrance
      method: get
      cors: true
      authorizer: 
        name: customauthorizer
        resultTtlInSeconds: 0
        identitySource: method.request.header.Authorization
