handler: handlers/tasks.updateTask
name: ${self:custom.constants.defaults.prefix}${self:service}-update
events:
  - http:
      path: /{id}
      method: put
      cors: true
      authorizer:
        name: customauthorizer
        resultTtlInSeconds: 0
        identitySource: method.request.header.Authorization
        #  documentation:
        #     summary: "Update Task"
        #     description: "Update an Task"
        #     requestBody:
        #       description: "Request body description"
        #     requestHeaders:
        #     -
        #       name: "Authorization"
        #       description: "Custom Authorizer Header Token"
        #     pathParams:
        #       -
        #         name: "id"
        #         required: true
        #         description: "ID of the attribute you want to update"
        #     requestModels:
        #       "application/json": "CreateRequest"
        #     methodResponses:
        #       -
        #         statusCode: "200"
        #         responseBody:
        #           description: "Response body description"
        #         responseHeaders:
        #           -
        #             name: "x-superheader"
        #             description: "this is a super header"
        #         responseModels:
        #           "application/json": "CreateResponse"
        #       -
        #         statusCode: "400"
        #         responseModels:
        #           "application/json": "ErrorResponse"
