handler: handlers/order.getOrdersCompletedForMobile
name: ${self:custom.constants.defaults.prefix}${self:service}-getOrdersCompletedForMobile
events:
  - http:
      path: /salesrep/completed
      method: get
      cors: true
      authorizer: 
        name: customauthorizer
        resultTtlInSeconds: 0
        identitySource: method.request.header.Authorization
