handler: handlers/products.getProductInventoryByThingUid
name: ${self:custom.constants.defaults.prefix}${self:service}-getProductInventoryByThingUid
events:
  - http:
      path: /inventory/thing/{uid}
      method: get
      cors: true
      authorizer:
        name: customauthorizer
        resultTtlInSeconds: 0
        identitySource: method.request.header.Authorization
