handler: handlers/products.getProductById
name: ${self:custom.constants.defaults.prefix}${self:service}-getByIdUnauth
events:
  - http:
      path: /detail/{id}
      method: get
      cors: true
      # authorizer:
      #   name: customauthorizer
      #   resultTtlInSeconds: 0
      #   identitySource: method.request.header.Authorization