handler: handlers/gateway.updateGateway
name: ${self:custom.constants.defaults.prefix}${self:service}-gateways-update
events:
  - http:
      path: /gateways/{id}
      method: put
      cors: true
      authorizer:
         name: customauthorizer
         resultTtlInSeconds: 0
         identitySource: method.request.header.Authorization