handler: routing/tags.routeTags
name: ${self:custom.constants.defaults.prefix}${self:service}-routeTags
events:
  - http:
      path: /{id}
      method: get
      cors: true
      authorizer:
        name: customauthorizer
        resultTtlInSeconds: 0
        identitySource: method.request.header.Authorization
  - http:
      path: /
      method: get
      cors: true
      authorizer: 
        name: customauthorizer
        resultTtlInSeconds: 0
        identitySource: method.request.header.Authorization
  
  - http:
      path: /{id}
      method: put
      cors: true
      authorizer: 
        name: customauthorizer
        resultTtlInSeconds: 0
        identitySource: method.request.header.Authorization

  - http:
      path: /
      method: post
      cors: true
      authorizer: 
        name: customauthorizer
        resultTtlInSeconds: 0
        identitySource: method.request.header.Authorization
