# service name
service: report

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

# all custom variables will only go under custom root. serverless does not allow any other root name
custom: 
  paths:
    configPath: "./../../../config/config"
    functionPath: "./../../../config/functions"

  constants: ${file(${self:custom.paths.configPath}/constants.serverless.yml)}

provider:
  # fixed - cannot change
  name: aws
  # fixed - cannot change
  runtime: nodejs6.10
  # default role for most of the functions for specific functions use role in function
  role: ${self:custom.constants.defaults.role}
  # default function versoning is on required for serverless-alias plugin
  versionFunctions: ${self:custom.constants.defaults.versionFunctions}
  stage: ${opt:stage, self:custom.constants.defaults.stage}
  region: ${self:custom.constants.defaults.region}
  memorySize: ${self:custom.constants.defaults.memorySize}
  timeout: ${self:custom.constants.defaults.timeout}
  deploymentBucket: ${self:custom.constants.defaults.deploymentBucketName}

  vpc: ${file(${self:custom.paths.configPath}/vpc.serverless.yml)}
  environment: ${file(${self:custom.paths.configPath}/environment.serverless.yml):${self:provider.alias}}

  # you can add packaging information here
package:
  include: ${file(${self:custom.paths.configPath}/includes.serverless.yml)}
  exclude: ${file(${self:custom.paths.configPath}/excludes.serverless.yml)}

plugins:
  - serverless-offline
  - serverless-aws-alias

resources:
  Resources:
    # change default generated api name
    ApiGatewayRestApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: ${self:custom.constants.defaults.prefix}${self:service}

functions:

  customauthorizer:
    handler: handlers/iam.customauthorizer
    name: ${self:custom.constants.defaults.prefix}${self:service}-authorizer


  routeReports: ${file(${self:custom.paths.functionPath}/report/reports.yml)}
  # getGraphReport:  ${file(${self:custom.paths.functionPath}/report/getGraphReport.yml)}
  # ordersPerHospital:  ${file(${self:custom.paths.functionPath}/report/ordersPerHospital.yml)}
  # ordersBySurgery:  ${file(${self:custom.paths.functionPath}/report/ordersBySurgery.yml)}
  # ordersNotClosed:  ${file(${self:custom.paths.functionPath}/report/ordersNotClosed.yml)}
  
  # ordersWithUnshippedProducts: ${file(${self:custom.paths.functionPath}/report/ordersWithUnshippedProducts.yml)}
  # undeliveredProducts: ${file(${self:custom.paths.functionPath}/report/undeliveredProducts.yml)}
  # orderspersurgeon: ${file(${self:custom.paths.functionPath}/report/orderspersurgeon.yml)}
  # shipmentDue: ${file(${self:custom.paths.functionPath}/report/shipmentDue.yml)}
  # ordersPerCity: ${file(${self:custom.paths.functionPath}/report/ordersByCity.yml)}
  # shipmentDeliveryTime: ${file(${self:custom.paths.functionPath}/report/shipmentDeliveryTime.yml)}
  # locationToZoneMaping: ${file(${self:custom.paths.functionPath}/report/locationToZoneMapping.yml)}
  # carrierWiseDelayedShipments: ${file(${self:custom.paths.functionPath}/report/carrierWiseDelayedShipments.yml)}
  # shipmentHardDelivered: ${file(${self:custom.paths.functionPath}/report/shipmentHardDelivered.yml)}
  # mostUsedProductsPerSurgeon : ${file(${self:custom.paths.functionPath}/report/mostUsedProductsPerSurgeon.yml)}
  # shipmentsInJeopardy: ${file(${self:custom.paths.functionPath}/report/shipmentsInJeopardy.yml)}
  # salesrepWiseProductOrder: ${file(${self:custom.paths.functionPath}/report/salesrepWiseProductOrder.yml)}
  # partialShipments: ${file(${self:custom.paths.functionPath}/report/partialShipments.yml)}
  # stationaryShipments: ${file(${self:custom.paths.functionPath}/report/stationaryShipments.yml)}
  # internalExternalShipment: ${file(${self:custom.paths.functionPath}/report/internalExternalShipment.yml)}
  # sensorConnectionStatus: ${file(${self:custom.paths.functionPath}/report/sensorConnectionStatus.yml)}
  # appStatus: ${file(${self:custom.paths.functionPath}/report/appStatus.yml)}
  # productsToDispatch: ${file(${self:custom.paths.functionPath}/report/productsToDispatch.yml)}
  # productThingMapping:  ${file(${self:custom.paths.functionPath}/report/productThingMapping.yml)}
  # productThingMappingHistory:  ${file(${self:custom.paths.functionPath}/report/productThingMappingHistory.yml)}
  # getLoginHistory: ${file(${self:custom.paths.functionPath}/report/loginHistory.yml)}
  # # userLocator:  ${file(${self:custom.paths.functionPath}/report/userLocator.yml)}
  
