handler: handlers/report.getGraphReport
name: ${self:custom.constants.defaults.prefix}${self:service}-get
events:
  - http:
      path: /get-graph-report
      method: get
      cors: true
      authorizer:
        name: customauthorizer
        resultTtlInSeconds: 0
        identitySource: method.request.header.Authorization