handler: handlers/report.loginHistory
name: ${self:custom.constants.defaults.prefix}${self:service}-getLoginHistory
events:
  - http:
      path: /login-history
      method: get
      cors: true
      authorizer:
        name: customauthorizer
        resultTtlInSeconds: 0
        identitySource: method.request.header.Authorization
