handler: handlers/report.orderspersurgeon
name: ${self:custom.constants.defaults.prefix}${self:service}-orderspersurgeon
events:
  - http:
      path: /orders-per-surgeon
      method: get
      cors: true
      authorizer:
        name: customauthorizer
        resultTtlInSeconds: 0
        identitySource: method.request.header.Authorization
