handler: handlers/report.ordersPerCity
name: ${self:custom.constants.defaults.prefix}${self:service}-ordersPerCity
events:
  - http:
      path: /orders-by-city
      method: get
      cors: true
      authorizer:
        name: customauthorizer
        resultTtlInSeconds: 0
        identitySource: method.request.header.Authorization
