handler: handlers/report.ordersBySurgery
name: ${self:custom.constants.defaults.prefix}${self:service}-ordersBySurgery
events:
  - http:
      path: /orders-by-surgery
      method: get
      cors: true
      authorizer:
        name: customauthorizer
        resultTtlInSeconds: 0
        identitySource: method.request.header.Authorization
