handler: handlers/report.ordersNotClosed
name: ${self:custom.constants.defaults.prefix}${self:service}-ordersNotClosed
events:
  - http:
      path: /orders-not-closed
      method: get
      cors: true
      authorizer:
        name: customauthorizer
        resultTtlInSeconds: 0
        identitySource: method.request.header.Authorization
