handler: handlers/report.partialShipments
name: ${self:custom.constants.defaults.prefix}${self:service}-partialShipments
events:
  - http:
      path: /partial-shipments
      method: get
      cors: true
      authorizer:
        name: customauthorizer
        resultTtlInSeconds: 0
        identitySource: method.request.header.Authorization
