handler: handlers/report.productThingMapping
name: ${self:custom.constants.defaults.prefix}${self:service}-productThingMapping
events:
  - http:
      path: /product-thing-mapping
      method: get
      cors: true
      authorizer:
        name: customauthorizer
        resultTtlInSeconds: 0
        identitySource: method.request.header.Authorization
