handler: routing/reports.routeReports
name: ${self:custom.constants.defaults.prefix}${self:service}-routeReports
events:
  - http:
      path: /{path}
      method: get
      cors: true
      authorizer:
        name: customauthorizer
        resultTtlInSeconds: 0
        identitySource: method.request.header.Authorization

  - http:
      path: /{path}/{id}
      method: get
      cors: true
      authorizer:
        name: customauthorizer
        resultTtlInSeconds: 0
        identitySource: method.request.header.Authorization
