handler: handlers/report.sensorConnectionStatus
name: ${self:custom.constants.defaults.prefix}${self:service}-sensorConnectionStatus
events:
  - http:
      path: /sensor-connection-status
      method: get
      cors: true
      authorizer:
        name: customauthorizer
        resultTtlInSeconds: 0
        identitySource: method.request.header.Authorization
