handler: handlers/report.shipmentsInJeopardy
name: ${self:custom.constants.defaults.prefix}${self:service}-shipmentsInJeopardy
events:
  - http:
      path: /shipments-in-jeopardy
      method: get
      cors: true
      authorizer:
        name: customauthorizer
        resultTtlInSeconds: 0
        identitySource: method.request.header.Authorization
