handler: handlers/report.shipmentDue
name: ${self:custom.constants.defaults.prefix}${self:service}-shipmentDue
events:
  - http:
      path: /shipment-due
      method: get
      cors: true
      authorizer:
        name: customauthorizer
        resultTtlInSeconds: 0
        identitySource: method.request.header.Authorization
