handler: handlers/report.undeliveredProducts
name: ${self:custom.constants.defaults.prefix}${self:service}-undeliveredProducts
events:
  - http:
      path: /undelivered-products
      method: get
      cors: true
      authorizer:
        name: customauthorizer
        resultTtlInSeconds: 0
        identitySource: method.request.header.Authorization
