handler: handlers/report.userLocator
name: ${self:custom.constants.defaults.prefix}${self:service}-userLocator
timeout: 30
events:
  - http:
      path: /user-locator
      method: get
      cors: true
      # authorizer: 
      #  name: customauthorizer
      #  resultTtlInSeconds: 0
      #  identitySource: method.request.header.Authorization
