# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'


target 'EmpTrak' do
   pod 'Fabric'
    pod 'Crashlytics'
    pod 'PhoneNumberKit' #, '~> 1.2'
    # pod 'DeviceKit','~>1.0'
    pod 'UrbanAirship-iOS-SDK'
    # pod 'SwiftSignatureView' #, '~>2.0'
    pod 'JTAppleCalendar', '~>7.0.1'
    pod 'Realm', '~>2.10.0'
    pod 'RealmSwift', '~>2.10.0'
    # pod 'JSQMessagesViewController', '~>7.3.4'
    #pod 'AWSLex', '~>2.5.4'
    pod 'AWSIoT' #,'~>2.5.0'
    pod 'AWSCore' #, '~> 2.5.0'
    pod 'AWSS3'
    pod 'SwiftyJSON'
    pod 'AWSCognitoIdentityProvider' #, '~> 2.5.10'
    pod 'JWTDecode'
    pod 'Cloudinary' #, '~> 2.0'
    # pod 'Google-Maps-iOS-SDK'
    pod 'APAddressBook/Swift' 
use_frameworks!

  # Pods for EmpTrak

end


