handler: handlers/location/zone.updateZone
name: ${self:custom.constants.defaults.prefix}${self:service}-updateZone
events:
  - http:
      path: /zones/{id}
      method: put
      cors: true
      authorizer:
         name: customauthorizer
         resultTtlInSeconds: 0
         identitySource: method.request.header.Authorization