handler: handlers/location/floor.getFloors
name: ${self:custom.constants.defaults.prefix}${self:service}-getFloor
events:
  - http:
      path: /floors
      method: get
      cors: true
      authorizer: 
        name: customauthorizer
        resultTtlInSeconds: 0
        identitySource: method.request.header.Authorization