handler: handlers/location/floor.saveFloor
name: ${self:custom.constants.defaults.prefix}${self:service}-saveFloor
events:
  - http:
      path: /floors
      method: post
      cors: true
      authorizer:
        name: customauthorizer
        resultTtlInSeconds: 0
        identitySource: method.request.header.Authorization