handler: handlers/location/floor.getFloorsInLocationInventory
name: ${self:custom.constants.defaults.prefix}${self:service}-getFloorsInLocationInventory
events:
  - http:
      path: /{id}/floors/inventory
      method: get
      cors: true
      # authorizer:
      #   name: customauthorizer
      #   resultTtlInSeconds: 0
      #   identitySource: method.request.header.Authorization
