

handler: handlers/emptrak.inOutHistory
name: ${self:custom.constants.defaults.prefix}${self:service}-inOutHistory
events:
  - http:
      path: /inouthistory
      method: get
      cors: true
      authorizer: 
        name: customauthorizer
        resultTtlInSeconds: 0
        identitySource: method.request.header.Authorization
